export const BUS_SEARCH_BEGIN   = 'BUS_SEARCH_BEGIN';
export const BUS_SEARCH_SUCCESS = 'BUS_SEARCH_SUCCESS';
export const BUS_SEARCH_FAILURE = 'BUS_SEARCH_FAILURE';

export const ADD_ARTICLE = "ADD_ARTICLE";